In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)

In [5]:
matriz = arr.reshape(2,5)

In [8]:
arr

array([ 1,  7,  6, 16, 11, 17,  4,  3, 12, 13])

In [6]:
arr.max() ## Me devuelve el valor maximo de mi array

17

In [10]:
matriz

array([[ 1,  7,  6, 16, 11],
       [17,  4,  3, 12, 13]])

In [12]:
matriz.max(0) ## Me devuelve el maximo por : si es 1 por fila, si es 0 por columnas 

array([17,  7,  6, 16, 13])

In [13]:
arr.argmax() ## Me devuelve en que posicion esta el valor maximo de mi array

5

In [14]:
matriz.argmax(0)## Me devuelve la posicion del maximo por : si es 1 por fila, si es 0 por columnas 

array([1, 0, 0, 0, 1])

In [15]:
arr.min() ## Me devuelve el valor minimo de mi array

1

In [16]:
matriz.min(0) ## Me devuelve el minimo por : si es 1 por fila, si es 0 por columnas 

array([ 1,  4,  3, 12, 11])

In [17]:
arr.argmin() ## Me devuelve en que posicion esta el valor minimo de mi array

0

In [19]:
matriz.argmin(1) ## Me devuelve la posicion del minimo por : si es 1 por fila, si es 0 por columnas

array([0, 2])

In [21]:
arr

array([ 1,  7,  6, 16, 11, 17,  4,  3, 12, 13])

In [20]:
arr.ptp() #La diferencia que hay entre el pico mas alto y el mas bajo

16

In [23]:
matriz.ptp(0) #La diferencia que hay entre el pico mas alto y el mas bajo --> Si indico 0: por columnas, Si indico 1: por filas

array([16,  3,  3,  4,  2])

In [32]:
arr.sort() ## Me ordena de menor a mayor el valor de mi arreglo
arr

array([ 1,  3,  4,  6,  7, 11, 12, 13, 16, 17])

In [30]:
np.percentile(arr,50) ## Me devuelve que yo indique --> Si indico 50: el valor de la mediana, Si indico 0: el valor minimo, Si indico 100: el valor maximo

17.0

In [33]:
np.median(arr) ## Retorna mediana de mi array, es el mismo resultado que percentil(<array>,50)

9.0

In [35]:
np.median(matriz,1) ## Retorna mediana de la matriz, dependiendo si le indico --> 0: es por columnas, 1: es por filas, si no indico nada me devuelve la mediana del total de la matriz

array([ 4., 13.])

In [38]:
np.std(arr) ** 2 ## Devuelve la desviacion estandar // La desviacion estandar al cuadro = varianza

28.000000000000004

In [37]:
np.var(arr) ## Retorna la varianza

28.0

In [39]:
np.mean(arr) ## Me devuelve la media. OJO: no confundir con la mediana!! La media es la sumatoria de todos los valores divido por la cantida de valores.
#La mediana es el valor mitad de mi intervalo.

9.0

In [54]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [44]:
np.concatenate((a,b),axis=0) ## Este error se da porque la dimension de b = 1 y la de a = 2, tiene que tener la misma dimension

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [55]:
a.ndim
b.ndim

1

In [56]:
b = np.expand_dims(b,axis=0) ## Expando dimension de b por columnas
b

array([[5, 6]])

In [57]:
np.concatenate((a,b),axis=0) # Concateno a y b por columnas.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
b

array([[5, 6]])

In [60]:
np.concatenate((a,b.T),axis=1) # Concateno a y b por filas --> Con el indicador T yo transpongo mi matriz

array([[1, 2, 5],
       [3, 4, 6]])

In [61]:
b.T ##Transpongo mi matriz, las filas pasan a ser columnas y viceversa.

array([[5],
       [6]])