In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))## Creo una matriz de 3x2 con numeros aleatorios del [1,10)

In [5]:
arr.shape ## Shape me dice cuantas filas y columnas tengo

(3, 2)

In [6]:
arr

array([[2, 9],
       [4, 6],
       [6, 8]])

In [7]:
arr.reshape(1,6) ## Redefino mi arreglo para que ahora sea un vector de 6 posiciones --> Cambio de forma

array([[2, 9, 4, 6, 6, 8]])

In [8]:
arr.reshape(2,3) ## Convierto a mi arreglo en una matriz de 2x3

array([[2, 9, 4],
       [6, 6, 8]])

In [9]:
np.reshape(arr,(1,6)) ## Otra manera de utilizar reshape

array([[2, 9, 4, 6, 6, 8]])

In [10]:
arr

array([[2, 9],
       [4, 6],
       [6, 8]])

In [11]:
np.reshape(arr,(2,3),'C') ## Reshape me convierte mi array en una matriz de 2x3 de la forma en que se haria en C --> Osea por filas

array([[2, 9, 4],
       [6, 6, 8]])

In [12]:
np.reshape(arr,(2,3),'F') ## Reshape me convierte mi array en una matriz de 2x3 de la forma en que se haria en Fortran --> Osea por columnas

array([[2, 6, 6],
       [4, 9, 8]])

In [13]:
np.reshape(arr,(2,3),'A') ## Reshape me convierte mi array en una matriz de 2x3 de la forma en que es mas optima en mi maquina --> Elije por C o Fotran


array([[2, 9, 4],
       [6, 6, 8]])

In [18]:
tensor = np.random.randint(1,10,(1,2,3,5))
tensor

array([[[[6, 3, 8, 1, 8],
         [6, 3, 9, 4, 8],
         [5, 4, 4, 5, 4]],

        [[5, 5, 2, 3, 3],
         [8, 1, 9, 9, 3],
         [9, 1, 9, 8, 5]]]])

In [20]:
tensor.shape

(1, 2, 3, 5)

In [24]:
np.reshape(tensor,(10,3))

array([[6, 3, 8],
       [1, 8, 6],
       [3, 9, 4],
       [8, 5, 4],
       [4, 5, 4],
       [5, 5, 2],
       [3, 3, 8],
       [1, 9, 9],
       [3, 9, 1],
       [9, 8, 5]])