In [1]:
import numpy as np

In [4]:
A = np.array([[2,4],[-1,2]])
Ainversa = np.linalg.inv(A)
Ainversa

array([[ 0.25 , -0.5  ],
       [ 0.125,  0.25 ]])

In [5]:
np.matmul(A, Ainversa)

array([[1., 0.],
       [0., 1.]])

In [8]:
A = np.array([[1,2],[1,0]])
values, vectors = np.linalg.eig(A)

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [10]:
np.matmul(A,vectors.T[1])
values[1]*vectors.T[1]

array([ 0.70710678, -0.70710678])