In [3]:
import numpy as np

In [1]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[1]

2

In [12]:
arr[0] + arr[5]

7

In [13]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matriz[0,2]

3

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [27]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[-3:]

array([7, 8, 9])

In [31]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [69]:
A = np.array([[1,4,5,12],[-5,8,9,0],[-6,7,11,19]])
A[:,0:2]

array([[ 1,  4],
       [-5,  8],
       [-6,  7]])

In [73]:
dimension3 = [[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]
dimension3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [74]:
dimension3 = np.array(dimension3)
dimension3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [75]:
dimension3[2]

array([[ 9, 10],
       [11, 12]])

In [76]:
dimension3[2,1]

array([11, 12])

In [77]:
dimension3[2,1,0]

11

In [78]:
dimension3[:2,::,1:]

array([[[2],
        [4]],

       [[6],
        [8]]])