In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype="int8") ## Creo un array int8 de 10 posiciones en el rango [1,10]
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
indices_cond = arr > 5 # Compara todos los objetos y me devuelve un array con True or False dependiendo si se cumple o no la condicion

In [9]:
arr[(arr > 5) & (arr < 9)] ## me devuelve solo los valores en donde la condicion es True

array([6, 7, 8], dtype=int8)

In [10]:
arr[arr > 5] = 99 ## Donde el valor es > 5, le asigno 99

In [11]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [13]:
arr[arr == 99] ## Me devuelve los valores = 99

array([99, 99, 99, 99, 99], dtype=int8)

In [15]:
arr == 99

array([False, False, False, False, False,  True,  True,  True,  True,
        True])