In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11) # Creo un array de [0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
trozo_de_arr = arr[0:6] ##Tomo 6 lugares desde mi array desde la posicion 0 // Tener en cuenta que sigo apuntando a mi array original

In [8]:
trozo_de_arr[:] = 0 # A todas mis posiciones le asigno el valor 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy() #Copio mi array a otro distinto, ya no referencio al mismo.

In [16]:
arr_copy[:] = 100 # Pongo 100 en todas las posiciones

In [17]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])