In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,20,2) #Me genera un array en el rango [0,20) de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros((10,5)) ## Me devuelve una matriz de 10x5 rellena de "0"

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((10,5)) ## Me devuelve una matriz de 10x5 rellena de "1"

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,100) ## Me devuelve 100 numeros en el rango [0,10] 

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4) ## Matriz escalonada

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(4) ## Me genera un array de tam = 4  con valores entre (0,1)

array([0.18657547, 0.55516164, 0.56087232, 0.99721292])

In [22]:
np.random.rand(4,4) ## Me genera una matriz de 4x4 con valores entre (0,1)

array([[0.47029601, 0.10619937, 0.96405787, 0.54158629],
       [0.86763441, 0.91264691, 0.38345788, 0.23851902],
       [0.43087357, 0.71052531, 0.07705151, 0.93672522],
       [0.17454466, 0.18082649, 0.62266146, 0.17980807]])

In [59]:
np.random.randint(1,15) ## Me genera un numero entero aleatorio entre [1,15)

3

In [60]:
np.random.randint(1,100,(10,10)) ## Me genera un matriz de 10x10 con valores entre [1,100)


array([[31, 14, 84, 99,  8, 20,  7, 35,  6, 49],
       [65, 81, 63, 76, 73, 83, 72, 77, 52, 56],
       [64,  3,  8, 65, 78, 45, 93, 47, 40, 86],
       [43, 94, 36,  2, 83, 98,  8, 73,  4, 76],
       [82, 69,  2,  7, 34, 19, 54, 83, 43, 77],
       [48, 11, 95, 32,  7, 10, 97, 84, 35, 15],
       [48, 75, 90,  8, 15, 26, 67, 61, 72, 35],
       [91, 83, 75, 69,  9, 40, 27, 33, 56, 38],
       [14, 11, 54, 43, 83, 51, 40, 99, 15, 65],
       [79, 51,  4, 83, 53, 65, 89, 36, 19, 15]])