In [1]:
import numpy as np

In [2]:
lista = [1,2] ## Creo una lista
lista

[1, 2]

In [3]:
lista * 2 # Me duplica mi lista

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10) ## Creo un array en el rango [0,10)
arr2 = arr.copy() # Copio mi array anterior

Operaciones 

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * 2 ## Mutiplico uno a uno los elementos del array.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr + 2 # Sumo 2 unidades a cada valor del array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
1 / arr # Divido 1 entre cada valor del array. NOTA: El error se da porque no se puede dividir por 0.

/tmp/ipykernel_6534/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr ** 2 # Sumo elevo al cuadrado a cada valor del array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr + arr2 # Sumo 2 arrays posicion a posicion.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr * arr2 # Mutiplico 2 arrays posicion a posicion.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [16]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz - matriz2 ## Resto los elementos de la matriz posicion a posicion. Todos los objetos deben tener la misma dimension para operar.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
matriz2.T # Traspongo la matriz2

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
np.matmul(matriz, matriz2.T) # Producto punto entre matrices.

array([[ 30,  80],
       [ 80, 255]])

# Producto Punto

El número de columnas de la primera matriz debe ser igual al número de filas de la 2da, para que se pueda realizar el producto.

En este caso:

 - Matriz: 2 x 5

   
  

 - Matriz2 (Traspuesta): 5 x 2

   
 

 - Matriz Resultante: 2 x 2


La matriz resultante tendrá como dimensión la cantidad de filas de la primera y la cantidad de columnas de la segunda.

> ***F: Fila C: Columna***

Para F:0 C: 0 --> Voy a multiplicar par a par la fila 0 de matriz por columna 0 de matriz2 y sumar sus resultados:

0*0 + 1 * 1 + 2 * 2 + 3 * 3 + 4 * 4 = 30 --> Esto ira en la posición F:0 C: 0 de la primera columna

Luego tomo: F:0 C:1 y repito, esto quedara en la posición F:0 C:1.

Repetir hasta recorrer la matriz completa.

In [24]:
matriz @ matriz2.T # Producto punto otra manera

array([[ 30,  80],
       [ 80, 255]])