In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [4]:
arr = np.array([1,2,3,4],dtype='float64')
arr.dtype

dtype('float64')

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

In [10]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [11]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [13]:
arr = np.array(['hola','0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'

In [16]:
np.arange(0,10,5)

array([0, 5])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])